### ISSUE TITLE
While using cmd + fwd-slash, the comment goes out of indentation

### ISSUE THREAD

**Issue by rahu1c** [cs50/sandbox#17]
I recently came across this issue in CS50 sandbox due to which I have to comment manually instead of the shortcut: cmd + forward-slash. While using the shortcut to comment, the forward slashes start at very beginning instead of preassigned indentation order thus requiring me to take an extra step of indenting code suitably. 
![issue](https://user-images.githubusercontent.com/13116007/51462687-42cc8180-1d87-11e9-9b3b-92d3a8075227.jpg)

**Comment by dmalan** [comment]
Thanks for the heads-up. Relayed to the team, do just keep an eye on https://feedback.codevolve.com/feature-requests/p/possible-for-command-to-respect-indentation-level!
