### ISSUE TITLE
Slight UI bug with terminal cursor

### ISSUE THREAD

**Issue by coderigo17** [cs50/sandbox#22]
Seems that when the terminal cursor is near the bottom of the screen, zooming in a few times (on a maximized window) and then zooming out can occasionally cause the cursor to be below visible range on the screen. Happened to me this morning, was able to reproduce it on Erin's computer, but tried a few times after on my computer and couldn't reproduce it again, so not sure how often this actually happens. Doesn't seem like a huge deal but maybe worth looking into?

**Comment by dmalan** [comment]
Do re-open if you see again and can screenshot!
