### ISSUE TITLE
Receive error message when running example files

### ISSUE THREAD

**Issue by cloaked-ninja** [cs50/sandbox#33]
Sandbox code looks like it is sometimes is not set up correctly.
Although example file already exists, won't run unless recompiled.

Steps to Reproduce:
1. Navigate to https://lab.cs50.io/cs50/labs/2019/fall/mario/less/
2. Follow link to example 'positive.c' file.  (Click "Hints" under Prompting for Input)
3. Type `ls `in console. Verify that _positive*_ and _positive.c_ are in the directory
4. Type `./positive`.  Error message will show: 
> /positive: error while loading shared libraries: libcs50.so.8.1.0: cannot open shared object file: No such file or directory
5. Type `make positive`
6. Type `./positive`.  Program runs correctly.

**Comment by dmalan** [comment]
Ah, thank you, @cloaked-ninja, will be fixed shortly!
