### ISSUE TITLE
Tab characters cannot be entered

### ISSUE THREAD

**Issue by stephendgilbert** [cs50/sandbox#37]
The tab characters in the editor get converted to spaces. I cannot find any way to enter a tab. Thus, I can't have my students write makefiles.

**Comment by dmalan** [comment]
Hi @stephendgilbert, thanks for the report. We reached out to the underlying cloud provider, and we're hoping they'll be able to special-case Makefiles soon, but in the meantime, they proposed some workarounds!

> For the time being there are a few workarounds:
>  * One is to configure the Makefile to use spaces instead of tabs, which is described here https://stackoverflow.com/questions/2131213/can-you-make-valid-makefiles-without-tab-characters/21920142. 
>  * Another workaround is to have the students run this command (or a similar one) in the terminal after making an edit to the Makefile. It will convert any amount of leading spaces to a single tab character. I haven't fully tested this so a variation of this command may be necessary:
>
>     `perl -p -i -e 's/^ +/\t/g' Makefile`
>  * Another workaround is to have the students edit the Makefile in the Terminal tab using vim or nano.

**Comment by dmalan** [comment]
Hi @stephendgilbert, tabs should no longer be converted to spaces in files named (case-insensitively) `GNUmakefile` or `Makefile`!
