### ISSUE TITLE
Update Java runtime to version `16.0.2` to match with check50's backend image and CS50 IDE

### ISSUE THREAD

**Issue by rongxin-liu** [cs50/sandbox#40]
Should we update Java runtime to version `16.0.2` to match with check50's backend image and CS50 IDE? @dmalan

**Comment by dmalan** [comment]
If we do, we should really update other versions as well, for parity with https://github.com/cs50/cli/?

**Comment by rongxin-liu** [comment]
Yes, this is already the case. check50 and CS50 IDE are now running `Java 16.0.2`.

**Comment by dmalan** [comment]
Oh I mean we should ideally update all of https://github.com/cs50/sandbox/blob/main/cs50.sh to match the installs in https://github.com/cs50/cli/blob/main/Dockerfile!

**Comment by rongxin-liu** [comment]
> Oh I mean we should ideally update all of https://github.com/cs50/sandbox/blob/main/cs50.sh to match the installs in https://github.com/cs50/cli/blob/main/Dockerfile!

Got it, made a PR!
https://github.com/cs50/sandbox/pull/41

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/sandbox/commit/f585ab2ffb48d6d39ee894b69a7c1fa9244e7a2a](https://github.com/cs50/sandbox/commit/f585ab2ffb48d6d39ee894b69a7c1fa9244e7a2a)
